import './globals.css'
import ReduxProvider from './components/reduxProvider'
import Header from './components/Header'  
export const metadata = {
  title: 'NETFlIX CLONE',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">  
      <ReduxProvider>
        <Header/> 
        {children}
     </ReduxProvider>
     </body>
    </html>
  )
}
